name: Trivy SCA Scan

on:
  push:
    branches:
      - main
      - develop
      - feature/**

  pull_request:
    branches:
      - main

jobs:
  trivy:
    name: Scan Dependencies

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Trivy Vulnerability Scanner
        uses: aquasecurity/trivy-action@v0.29.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          severity: 'HIGH,CRITICAL'
          exit-code: '1'